(() => {
  const apiBase=String(window.GOY_ADMIN_CONFIG?.apiBaseUrl||'/api').replace(/\/$/,'');
  const token=()=>sessionStorage.getItem('goyAdminToken')||'';
  const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  let clients=[];

  const style=document.createElement('style');style.textContent=`
    .goy-bank-section{margin:18px 0;padding:16px;border:1px solid #dce9ee;background:#f8fbfc;border-radius:16px}.goy-bank-head{display:flex;justify-content:space-between;gap:12px;align-items:center;margin-bottom:12px}.goy-bank-head h4{margin:0}.goy-bank-add{border:0;background:#0b8fc2;color:#fff;border-radius:10px;padding:9px 12px;font-weight:900;cursor:pointer}.goy-bank-list{display:grid;gap:10px}.goy-bank-card{background:#fff;border:1px solid #e2ecef;border-radius:13px;padding:12px;display:grid;grid-template-columns:1fr auto;gap:10px}.goy-bank-card small{display:block;color:#758995;margin-top:3px}.goy-bank-remove{border:1px solid #f0caca;background:#fff5f5;color:#a52a2a;border-radius:9px;padding:7px 9px;font-weight:800;cursor:pointer}.goy-bank-empty{color:#748892;background:#fff;border:1px dashed #cddde4;border-radius:12px;padding:14px;text-align:center}.goy-bank-form{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:12px}.goy-bank-form input,.goy-bank-form select{width:100%;box-sizing:border-box;padding:10px 11px;border:1px solid #cadbe2;border-radius:10px;font:inherit}.goy-bank-form .wide{grid-column:1/-1}.goy-bank-form-actions{grid-column:1/-1;display:flex;justify-content:flex-end;gap:8px}.goy-bank-form-actions button{border:0;border-radius:9px;padding:9px 12px;font-weight:900;cursor:pointer}.goy-bank-save{background:#0b8fc2;color:#fff}.goy-bank-cancel{background:#edf4f6;color:#294957}.goy-bank-msg{grid-column:1/-1;font-size:12px;font-weight:800;min-height:16px}@media(max-width:620px){.goy-bank-form{grid-template-columns:1fr}.goy-bank-form .wide,.goy-bank-form-actions,.goy-bank-msg{grid-column:auto}}
  `;document.head.appendChild(style);

  async function api(path,options={}){const r=await fetch(`${apiBase}${path}`,{...options,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token()}`,...(options.headers||{})}});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'No se pudo guardar la cuenta bancaria.');return b;}
  async function load(){if(!token())return;try{const b=await api('/admin/data');clients=b.clients||[];}catch{}}
  function findClient(modal){const title=String(modal.querySelector('.client-detail-head h3')?.textContent||'').trim().toLowerCase();return clients.find(c=>String(c.businessName||c.name||'').trim().toLowerCase()===title)||null;}
  function renderList(section,client){const list=section.querySelector('.goy-bank-list'),accounts=Array.isArray(client.bankAccounts)?client.bankAccounts:[];list.innerHTML=accounts.length?accounts.map((a,i)=>`<div class="goy-bank-card"><div><strong>${esc(a.bank||'Banco no indicado')}</strong><small>${esc(a.accountType||'Cuenta')} · ${esc(a.accountNumber||'Sin número')}</small><small>Titular: ${esc(a.holderName||'-')} · ID: ${esc(a.holderDocument||'-')}</small>${a.notes?`<small>${esc(a.notes)}</small>`:''}</div><button class="goy-bank-remove" data-bank-index="${i}" type="button">Eliminar</button></div>`).join(''):'<div class="goy-bank-empty">No hay cuentas bancarias registradas para este cliente.</div>';}
  async function saveAccounts(client,accounts){await api(`/admin/clients/${encodeURIComponent(client.userId||client.id)}`,{method:'PATCH',body:JSON.stringify({bankAccounts:accounts})});client.bankAccounts=accounts;}
  function showForm(section,client){if(section.querySelector('.goy-bank-form'))return;const form=document.createElement('form');form.className='goy-bank-form';form.innerHTML=`<input name="bank" required placeholder="Banco"><select name="accountType"><option value="">Tipo de cuenta</option><option>Ahorros</option><option>Corriente</option></select><input name="accountNumber" required placeholder="Número de cuenta"><input name="holderName" required placeholder="Titular"><input class="wide" name="holderDocument" placeholder="Cédula / RUC del titular"><input class="wide" name="notes" placeholder="Nota opcional"><div class="goy-bank-msg"></div><div class="goy-bank-form-actions"><button type="button" class="goy-bank-cancel">Cancelar</button><button type="submit" class="goy-bank-save">Guardar cuenta</button></div>`;section.appendChild(form);form.querySelector('.goy-bank-cancel').onclick=()=>form.remove();form.addEventListener('submit',async e=>{e.preventDefault();const msg=form.querySelector('.goy-bank-msg'),fd=new FormData(form),account={bank:String(fd.get('bank')||'').trim(),accountType:String(fd.get('accountType')||'').trim(),accountNumber:String(fd.get('accountNumber')||'').trim(),holderName:String(fd.get('holderName')||'').trim(),holderDocument:String(fd.get('holderDocument')||'').trim(),notes:String(fd.get('notes')||'').trim()};msg.textContent='Guardando…';try{const accounts=[...(client.bankAccounts||[]),account];await saveAccounts(client,accounts);renderList(section,client);form.remove();}catch(err){msg.textContent=err.message;}});}
  function decorateModal(){const modal=document.getElementById('goyClientDetailModal');if(!modal||modal.dataset.bankReady==='1')return;const card=modal.querySelector('.client-detail-modal');if(!card)return;const client=findClient(modal);if(!client)return;modal.dataset.bankReady='1';const section=document.createElement('section');section.className='goy-bank-section';section.innerHTML='<div class="goy-bank-head"><h4>Cuentas bancarias</h4><button class="goy-bank-add" type="button">＋ Agregar cuenta</button></div><div class="goy-bank-list"></div>';const historyTitle=[...card.querySelectorAll('h4')].find(x=>x.textContent.includes('Carreras'));if(historyTitle)card.insertBefore(section,historyTitle);else card.appendChild(section);renderList(section,client);section.querySelector('.goy-bank-add').onclick=()=>showForm(section,client);section.addEventListener('click',async e=>{const b=e.target.closest('[data-bank-index]');if(!b)return;const i=Number(b.dataset.bankIndex);if(!confirm('¿Eliminar esta cuenta bancaria del cliente?'))return;try{const accounts=(client.bankAccounts||[]).filter((_,idx)=>idx!==i);await saveAccounts(client,accounts);renderList(section,client);}catch(err){alert(err.message);}});}
  const obs=new MutationObserver(()=>decorateModal());obs.observe(document.body,{childList:true,subtree:true});load().then(decorateModal);document.addEventListener('click',e=>{if(e.target.closest('[data-view="clients"],[data-go="clients"]'))setTimeout(load,120);});
})();
