'use strict';
const crypto=require('crypto');
const {createProspect,processInbound,serviceReply,canSendOutbound,firstContact,scheduleFollowUp}=require('./sales-assistant');

const CRM_KEYS=['prospects','salesMessages','salesAppointments','salesCampaigns'];
function ensureCrm(data){for(const key of CRM_KEYS)if(!Array.isArray(data[key]))data[key]=[];return data;}
function findProspect(data,idOrPhone){const value=String(idOrPhone||'').replace(/\D/g,'');return data.prospects.find(p=>p.id===idOrPhone||p.phone===value)||null;}
function importProspects(data,rows=[]){ensureCrm(data);const created=[],skipped=[];for(const row of rows){try{const p=createProspect(row);if(data.prospects.some(x=>x.phone===p.phone)){skipped.push({phone:p.phone,reason:'duplicate'});continue;}data.prospects.unshift(p);created.push(p);}catch(error){skipped.push({phone:row?.phone||row?.whatsapp||'',reason:error.message});}}return {created,skipped};}
function addMessage(data,{prospectId,direction,text,providerId=null,status='recorded'}){ensureCrm(data);const item={id:crypto.randomUUID(),prospectId,direction,text:String(text||''),providerId,status,createdAt:new Date().toISOString()};data.salesMessages.unshift(item);return item;}
function receiveMessage(data,prospect,message){ensureCrm(data);addMessage(data,{prospectId:prospect.id,direction:'inbound',text:message});const result=processInbound(prospect,message);const index=data.prospects.findIndex(p=>p.id===prospect.id);if(index>=0)data.prospects[index]=result.prospect;const reply=result.reply||serviceReply(result.prospect,result.service);addMessage(data,{prospectId:prospect.id,direction:'outbound_pending',text:reply,status:'pending'});return {...result,reply};}
function queueFirstContact(data,prospect){ensureCrm(data);if(!canSendOutbound(prospect))return {ok:false,reason:'consent_required'};const text=firstContact(prospect);prospect.status='Contactado';prospect.lastOutboundAt=new Date().toISOString();Object.assign(prospect,scheduleFollowUp(prospect,24));const message=addMessage(data,{prospectId:prospect.id,direction:'outbound_pending',text,status:'pending'});return {ok:true,message};}
function recordAppointment(data,prospect,input={}){ensureCrm(data);const item={id:crypto.randomUUID(),prospectId:prospect.id,type:input.type==='video'?'video':'call',startTime:String(input.startTime||''),endTime:String(input.endTime||''),calendarEventId:String(input.calendarEventId||''),meetUrl:String(input.meetUrl||''),status:'scheduled',createdAt:new Date().toISOString()};data.salesAppointments.unshift(item);prospect.meeting=item;prospect.status='Reunión agendada';prospect.nextFollowUpAt=null;prospect.updatedAt=new Date().toISOString();return item;}
function metrics(data){ensureCrm(data);const byStatus={};for(const p of data.prospects)byStatus[p.status]=(byStatus[p.status]||0)+1;return {total:data.prospects.length,byStatus,optedOut:data.prospects.filter(p=>p.optedOut).length,meetings:data.salesAppointments.filter(a=>a.status==='scheduled').length,pendingMessages:data.salesMessages.filter(m=>m.status==='pending').length};}
module.exports={ensureCrm,findProspect,importProspects,addMessage,receiveMessage,queueFirstContact,recordAppointment,metrics};