(()=>{
  const apiBase=String(window.GOY_ADMIN_CONFIG?.apiBaseUrl||'/api').replace(/\/$/,'');
  const token=()=>sessionStorage.getItem('goyAdminToken')||'';
  const esc=v=>String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]));
  const money=v=>`$${Number(v||0).toFixed(2)}`;
  const serviceName=o=>o?.serviceLabel||({shipment:o?.deliveryMode==='express'?'Envío Express':'Entrega programada',procedure:'Trámite ejecutivo',deposit:'Depósito',diverse:'Servicio diverso',office_pickup:'Retiro oficina',partner:'Plan inicial'}[o?.kind])||o?.service||o?.kind||'Servicio';
  let all=[],cycles=[],activeCycle='';

  async function api(path){const r=await fetch(`${apiBase}${path}`,{headers:{Authorization:`Bearer ${token()}`}});const b=await r.json().catch(()=>({}));if(!r.ok)throw new Error(b.error||'No se pudieron cargar los reportes.');return b;}
  const uniq=arr=>[...new Set(arr.filter(Boolean).map(String))].sort((a,b)=>a.localeCompare(b,'es'));
  const safe=v=>String(v||'general').normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^-+|-+$/g,'').toLowerCase()||'general';
  function selectedRows(){const type=document.getElementById('goyReportType')?.value||'general',value=document.getElementById('goyReportValue')?.value||'';return all.filter(o=>{if(type==='client')return String(o.customer||o.businessName||o.client||'')===value;if(type==='courier')return String(o.courier||'Sin asignar')===value;if(type==='service')return serviceName(o)===value;return true;});}
  function headers(){return ['Período','Solicitud','Cliente','Servicio','Dirección','Mensajero','Estado','Tarifa','Min espera extra','Recargo espera','Depositado','Cartera liberada'];}
  function row(o){return [o.cycleKey||activeCycle,o.code||o.id||'-',o.customer||o.businessName||o.client||'-',serviceName(o),o.destinationAddress||o.pickupAddress||o.address||'-',o.courier||'Sin asignar',o.status||'Pendiente',Number(o.serviceCost??o.value??0),Number(o.wait?.extraMinutes||0),Number(o.wait?.extraCost||0),Number(o.wallet?.depositedAmount||0),o.wallet?.released?'Sí':'No'];}
  function fileBase(){const type=document.getElementById('goyReportType')?.value||'general',value=document.getElementById('goyReportValue')?.value||'';return `goy-xpress-${activeCycle||'reporte'}-${type==='general'?'general':safe(value)}`;}
  function downloadBlob(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  function downloadCsv(){const rows=selectedRows();const csv=[headers(),...rows.map(row)].map(r=>r.map(v=>`"${String(v).replace(/"/g,'""')}"`).join(',')).join('\n');downloadBlob(new Blob(['\ufeff'+csv],{type:'text/csv;charset=utf-8'}),`${fileBase()}.csv`);}
  function downloadExcel(){const rows=selectedRows(),h=headers();const html=`<html><head><meta charset="utf-8"></head><body><h2>GOY XPRESS · Reporte</h2><p>Período: ${esc(activeCycle||'-')}</p><table border="1"><tr>${h.map(x=>`<th>${esc(x)}</th>`).join('')}</tr>${rows.map(o=>`<tr>${row(o).map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</table></body></html>`;downloadBlob(new Blob(['\ufeff'+html],{type:'application/vnd.ms-excel'}),`${fileBase()}.xls`);}
  function printReport(){const rows=selectedRows(),h=headers(),w=window.open('','_blank','width=1100,height=800');if(!w)return alert('Permite ventanas emergentes para imprimir el reporte.');w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>Reporte GOY XPRESS</title><style>body{font-family:Arial;padding:18px;color:#122b36}table{border-collapse:collapse;width:100%;font-size:10px}th,td{border:1px solid #ccd9de;padding:6px;text-align:left}th{background:#eef5f7}@media print{@page{size:A4 landscape;margin:8mm}}</style></head><body><h2>GOY XPRESS · Reporte</h2><p>Período: ${esc(activeCycle||'-')} · ${rows.length} registro(s)</p><table><tr>${h.map(x=>`<th>${esc(x)}</th>`).join('')}</tr>${rows.map(o=>`<tr>${row(o).map(v=>`<td>${esc(v)}</td>`).join('')}</tr>`).join('')}</table><script>window.onload=()=>setTimeout(()=>window.print(),250)<\/script></body></html>`);w.document.close();}
  function optionsFor(type){if(type==='client')return uniq(all.map(o=>o.customer||o.businessName||o.client||''));if(type==='courier')return uniq(all.map(o=>o.courier||'Sin asignar'));if(type==='service')return uniq(all.map(serviceName));return [];}
  function updateValueOptions(){const type=document.getElementById('goyReportType')?.value||'general',select=document.getElementById('goyReportValue'),wrap=document.getElementById('goyReportValueWrap');if(!select||!wrap)return;if(type==='general'){wrap.style.display='none';select.innerHTML='';}else{wrap.style.display='block';select.innerHTML=optionsFor(type).map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('');}updateSummary();}
  function updateSummary(){const rows=selectedRows(),sum=document.getElementById('goyReportFilteredSummary');if(!sum)return;sum.textContent=`${rows.length} registro(s) · Total tarifas ${money(rows.reduce((s,o)=>s+Number(o.serviceCost??o.value??0),0))}`;}
  async function loadCycle(cycle){const b=await api(`/admin/data${cycle?`?cycle=${encodeURIComponent(cycle)}`:''}`);all=b.requests||[];activeCycle=b.activeCycle||cycle||'';cycles=b.availableCycles||[];render();}
  function render(){const section=document.getElementById('reports');if(!section||!token())return;let box=document.getElementById('goyAdvancedReports');if(!box){box=document.createElement('div');box.id='goyAdvancedReports';box.className='panel';box.style.marginTop='14px';section.appendChild(box);}box.innerHTML=`<div class="panel-head"><div><span class="eyebrow">Reportes personalizados</span><h3>Descargar información específica</h3><p class="muted">Elige el período y genera un reporte general o filtrado.</p></div></div><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:10px;align-items:end"><label>Período<select id="goyReportCycle">${(cycles.length?cycles:[activeCycle]).filter(Boolean).map(c=>`<option value="${esc(c)}" ${c===activeCycle?'selected':''}>${esc(c)}</option>`).join('')}</select></label><label>Tipo de reporte<select id="goyReportType"><option value="general">General</option><option value="client">Solo por cliente</option><option value="courier">Solo por mensajero</option><option value="service">Solo por servicio</option></select></label><label id="goyReportValueWrap" style="display:none">Seleccionar<select id="goyReportValue"></select></label></div><div id="goyReportFilteredSummary" style="margin:12px 0;font-weight:800;color:#315361"></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button id="goyReportExcel" class="primary">Descargar Excel</button><button id="goyReportCsv" class="ghost">Descargar CSV</button><button id="goyReportPrint" class="ghost">Guardar PDF / imprimir</button></div>`;
    document.getElementById('goyReportCycle').onchange=e=>loadCycle(e.target.value).catch(err=>alert(err.message));
    document.getElementById('goyReportType').onchange=updateValueOptions;
    document.getElementById('goyReportValue').onchange=updateSummary;
    document.getElementById('goyReportExcel').onclick=downloadExcel;
    document.getElementById('goyReportCsv').onclick=downloadCsv;
    document.getElementById('goyReportPrint').onclick=printReport;
    updateValueOptions();
  }
  async function init(){if(!token())return;try{await loadCycle('');}catch(e){console.warn('GOY reportes:',e.message);}}
  document.addEventListener('click',e=>{if(e.target.closest('[data-view="reports"],[data-go="reports"]'))setTimeout(init,120);});
  setTimeout(init,900);
})();