import React,{useEffect,useMemo,useState}from'react';
import{Image,Modal,Pressable,ScrollView,StyleSheet,Text,View}from'react-native';
import{getClientRequests}from'./goyApiV5';

const C={navy:'#071C2A',cyan:'#00A9E8',green:'#38A844',white:'#fff',ink:'#132B36',muted:'#687D88',line:'#DCE8ED',bg:'#F4F8FA'};
const valid=v=>/^data:image\/(jpeg|jpg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(String(v||''));
function photosOf(r){const e=r?.evidence||{};return[['Retiro',e.pickupPhoto],['Entrega',e.deliveryPhoto],['Depósito',e.depositPhoto||r?.wallet?.depositPhoto]].filter(([,src])=>valid(src));}

export default function ClientEvidenceOverlay({token}){
  const[open,setOpen]=useState(false),[items,setItems]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const load=async()=>{if(!token||busy)return;setBusy(true);setError('');try{setItems(await getClientRequests(token))}catch(e){setError(e.message||'No se pudieron cargar las evidencias.')}finally{setBusy(false)}};
  useEffect(()=>{if(open)load()},[open,token]);
  const evidence=useMemo(()=>items.map(r=>({request:r,photos:photosOf(r)})).filter(x=>x.photos.length),[items]);
  return <>
    <Pressable accessibilityRole="button" accessibilityLabel="Ver fotos de mis entregas" onPress={()=>setOpen(true)} style={({pressed})=>[s.fab,pressed&&{opacity:.82}]}><Text style={s.fabIcon}>📷</Text><Text style={s.fabText}>Fotos</Text></Pressable>
    <Modal visible={open} animationType="slide" transparent onRequestClose={()=>setOpen(false)}><View style={s.backdrop}><View style={s.sheet}><View style={s.head}><View style={{flex:1}}><Text style={s.kicker}>EVIDENCIAS</Text><Text style={s.title}>Fotos de mis servicios</Text><Text style={s.note}>Fotografías registradas por el mensajero durante retiro, entrega o depósito.</Text></View><Pressable onPress={()=>setOpen(false)} style={s.close}><Text style={s.closeText}>×</Text></Pressable></View><ScrollView contentContainerStyle={s.body}>{busy?<Text style={s.empty}>Actualizando fotografías…</Text>:error?<><Text style={s.error}>{error}</Text><Pressable onPress={load} style={s.refresh}><Text style={s.refreshText}>Reintentar</Text></Pressable></>:evidence.length?evidence.map(({request,photos})=><View key={request.code||request.id} style={s.card}><View style={s.cardHead}><View><Text style={s.code}>{request.code||request.id}</Text><Text style={s.status}>{request.status||'Solicitud'}</Text></View><Text style={s.count}>{photos.length} foto(s)</Text></View><View style={s.grid}>{photos.map(([label,src])=><View key={label} style={s.photoCard}><Image source={{uri:src}} style={s.photo} resizeMode="cover"/><Text style={s.photoLabel}>{label}</Text></View>)}</View></View>):<Text style={s.empty}>Todavía no hay fotografías registradas por el mensajero.</Text>}</ScrollView><Pressable onPress={load} disabled={busy} style={[s.refresh,busy&&{opacity:.5}]}><Text style={s.refreshText}>↻ Actualizar fotos</Text></Pressable></View></View></Modal>
  </>;
}

const s=StyleSheet.create({fab:{position:'absolute',right:16,bottom:92,zIndex:999,backgroundColor:C.navy,borderRadius:18,paddingHorizontal:14,paddingVertical:10,flexDirection:'row',alignItems:'center',gap:7,shadowColor:'#000',shadowOpacity:.22,shadowRadius:10,elevation:8},fabIcon:{fontSize:17},fabText:{color:C.white,fontWeight:'900'},backdrop:{flex:1,backgroundColor:'#041820AA',justifyContent:'flex-end'},sheet:{maxHeight:'88%',backgroundColor:C.bg,borderTopLeftRadius:26,borderTopRightRadius:26,padding:16},head:{flexDirection:'row',gap:12,alignItems:'flex-start'},kicker:{color:C.cyan,fontSize:10,fontWeight:'900',letterSpacing:1},title:{color:C.ink,fontSize:23,fontWeight:'900',marginTop:3},note:{color:C.muted,fontSize:12,lineHeight:18,marginTop:4},close:{width:42,height:42,borderRadius:14,backgroundColor:C.white,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:C.line},closeText:{fontSize:28,color:C.navy,lineHeight:30},body:{paddingVertical:14,paddingBottom:20},card:{backgroundColor:C.white,borderRadius:18,padding:13,borderWidth:1,borderColor:C.line,marginBottom:12},cardHead:{flexDirection:'row',justifyContent:'space-between',gap:10,alignItems:'center'},code:{fontWeight:'900',color:C.navy,fontSize:15},status:{color:C.muted,fontSize:11,marginTop:2},count:{color:C.green,fontWeight:'900',fontSize:11},grid:{flexDirection:'row',flexWrap:'wrap',gap:10,marginTop:12},photoCard:{width:'48%',minWidth:140},photo:{width:'100%',aspectRatio:4/3,borderRadius:13,backgroundColor:'#E7EFF2'},photoLabel:{color:C.ink,fontWeight:'900',fontSize:11,marginTop:6},empty:{textAlign:'center',color:C.muted,paddingVertical:35,fontWeight:'700'},error:{textAlign:'center',color:'#B42318',paddingVertical:18,fontWeight:'800'},refresh:{backgroundColor:C.cyan,borderRadius:13,paddingVertical:12,alignItems:'center',marginTop:6},refreshText:{color:C.white,fontWeight:'900'}});