import React,{useEffect,useMemo,useState}from'react';
import{Image,Modal,Pressable,ScrollView,StyleSheet,Text,View}from'react-native';
import{getClientRequests}from'./goyApiV5';

const C={navy:'#071C2A',cyan:'#00A9E8',green:'#38A844',white:'#fff',ink:'#132B36',muted:'#687D88',line:'#DCE8ED',bg:'#F4F8FA'};
const valid=v=>/^data:image\/(jpeg|jpg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(String(v||''));
const LABELS={pickup:'Retiro',service:'Durante el servicio',delivery:'Entrega',deposit:'Depósito'};
function photosOf(r){
  const e=r?.evidence||{},out=[];
  const add=(label,src,at='')=>{if(valid(src))out.push({label,src,at})};
  add('Retiro',e.pickupPhoto,e.pickupAt);
  add('Entrega',e.deliveryPhoto,e.deliveryAt);
  add('Depósito',e.depositPhoto||r?.wallet?.depositPhoto,e.depositAt||r?.wallet?.depositedAt);
  const extra=e.additional||{};
  Object.entries(extra).forEach(([type,list])=>{
    (Array.isArray(list)?list:[]).forEach((item,index)=>add(`${LABELS[type]||'Evidencia'} adicional ${index+1}`,item?.photo,item?.at));
  });
  return out;
}
function when(v){if(!v)return'';try{return new Date(v).toLocaleString('es-EC',{dateStyle:'short',timeStyle:'short'})}catch{return''}}

export default function ClientEvidenceOverlay({token}){
  const[open,setOpen]=useState(false),[items,setItems]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[updated,setUpdated]=useState(null);
  const load=async(silent=false)=>{if(!token||busy)return;if(!silent)setBusy(true);setError('');try{setItems(await getClientRequests(token));setUpdated(new Date())}catch(e){if(!silent)setError(e.message||'No se pudieron cargar las evidencias.')}finally{if(!silent)setBusy(false)}};
  useEffect(()=>{if(!open)return;load();const id=setInterval(()=>load(true),12000);return()=>clearInterval(id)},[open,token]);
  const evidence=useMemo(()=>items.map(r=>({request:r,photos:photosOf(r)})).filter(x=>x.photos.length),[items]);
  const total=useMemo(()=>evidence.reduce((n,x)=>n+x.photos.length,0),[evidence]);
  return <>
    <Pressable accessibilityRole="button" accessibilityLabel="Ver fotos subidas por el mensajero" onPress={()=>setOpen(true)} style={({pressed})=>[s.fab,pressed&&{opacity:.82}]}><Text style={s.fabIcon}>📷</Text><Text style={s.fabText}>Fotos mensajero</Text>{total?<View style={s.badge}><Text style={s.badgeText}>{total}</Text></View>:null}</Pressable>
    <Modal visible={open} animationType="slide" transparent onRequestClose={()=>setOpen(false)}><View style={s.backdrop}><View style={s.sheet}><View style={s.head}><View style={{flex:1}}><Text style={s.kicker}>EVIDENCIAS DEL MENSAJERO</Text><Text style={s.title}>Fotos de mis servicios</Text><Text style={s.note}>Aquí puedes ver las fotografías que el mensajero sube en el retiro, durante el servicio, en la entrega y en depósitos.</Text>{updated?<Text style={s.updated}>Actualizado: {updated.toLocaleTimeString('es-EC',{hour:'2-digit',minute:'2-digit'})}</Text>:null}</View><Pressable onPress={()=>setOpen(false)} style={s.close}><Text style={s.closeText}>×</Text></Pressable></View><ScrollView contentContainerStyle={s.body}>{busy?<Text style={s.empty}>Actualizando fotografías…</Text>:error?<><Text style={s.error}>{error}</Text><Pressable onPress={()=>load()} style={s.refresh}><Text style={s.refreshText}>Reintentar</Text></Pressable></>:evidence.length?evidence.map(({request,photos})=><View key={request.code||request.id} style={s.card}><View style={s.cardHead}><View style={{flex:1}}><Text style={s.code}>{request.code||request.id}</Text><Text style={s.status}>{request.status||'Solicitud'}</Text></View><View style={s.countPill}><Text style={s.count}>{photos.length} foto(s)</Text></View></View><View style={s.grid}>{photos.map((p,index)=><View key={`${p.label}-${index}`} style={s.photoCard}><Image source={{uri:p.src}} style={s.photo} resizeMode="cover"/><Text style={s.photoLabel}>{p.label}</Text>{p.at?<Text style={s.photoDate}>{when(p.at)}</Text>:null}</View>)}</View></View>):<View style={s.emptyBox}><Text style={s.emptyIcon}>📷</Text><Text style={s.emptyTitle}>Todavía no hay fotos</Text><Text style={s.empty}>Cuando el mensajero suba una evidencia aparecerá aquí automáticamente.</Text></View>}</ScrollView><Pressable onPress={()=>load()} disabled={busy} style={[s.refresh,busy&&{opacity:.5}]}><Text style={s.refreshText}>↻ Actualizar fotos</Text></Pressable></View></View></Modal>
  </>;
}

const s=StyleSheet.create({fab:{position:'absolute',right:16,bottom:92,zIndex:999,backgroundColor:C.navy,borderRadius:18,paddingHorizontal:14,paddingVertical:10,flexDirection:'row',alignItems:'center',gap:7,shadowColor:'#000',shadowOpacity:.22,shadowRadius:10,elevation:8},fabIcon:{fontSize:17},fabText:{color:C.white,fontWeight:'900'},badge:{minWidth:22,height:22,borderRadius:11,backgroundColor:C.green,alignItems:'center',justifyContent:'center',paddingHorizontal:5},badgeText:{color:C.white,fontWeight:'900',fontSize:10},backdrop:{flex:1,backgroundColor:'#041820AA',justifyContent:'flex-end'},sheet:{maxHeight:'90%',backgroundColor:C.bg,borderTopLeftRadius:26,borderTopRightRadius:26,padding:16},head:{flexDirection:'row',gap:12,alignItems:'flex-start'},kicker:{color:C.cyan,fontSize:10,fontWeight:'900',letterSpacing:1},title:{color:C.ink,fontSize:23,fontWeight:'900',marginTop:3},note:{color:C.muted,fontSize:12,lineHeight:18,marginTop:4},updated:{color:C.green,fontSize:10,fontWeight:'800',marginTop:6},close:{width:42,height:42,borderRadius:14,backgroundColor:C.white,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:C.line},closeText:{fontSize:28,color:C.navy,lineHeight:30},body:{paddingVertical:14,paddingBottom:20},card:{backgroundColor:C.white,borderRadius:18,padding:13,borderWidth:1,borderColor:C.line,marginBottom:12},cardHead:{flexDirection:'row',justifyContent:'space-between',gap:10,alignItems:'center'},code:{fontWeight:'900',color:C.navy,fontSize:15},status:{color:C.muted,fontSize:11,marginTop:2},countPill:{backgroundColor:'#EAF8ED',borderRadius:999,paddingHorizontal:10,paddingVertical:6},count:{color:C.green,fontWeight:'900',fontSize:11},grid:{flexDirection:'row',flexWrap:'wrap',gap:10,marginTop:12},photoCard:{width:'48%',minWidth:140},photo:{width:'100%',aspectRatio:4/3,borderRadius:13,backgroundColor:'#E7EFF2'},photoLabel:{color:C.ink,fontWeight:'900',fontSize:11,marginTop:6},photoDate:{color:C.muted,fontSize:9,marginTop:2},emptyBox:{alignItems:'center',paddingVertical:30},emptyIcon:{fontSize:36},emptyTitle:{fontWeight:'900',color:C.ink,fontSize:17,marginTop:8},empty:{textAlign:'center',color:C.muted,paddingVertical:10,fontWeight:'700',lineHeight:18},error:{textAlign:'center',color:'#B42318',paddingVertical:18,fontWeight:'800'},refresh:{backgroundColor:C.cyan,borderRadius:13,paddingVertical:12,alignItems:'center',marginTop:6},refreshText:{color:C.white,fontWeight:'900'}});