import React,{useEffect,useMemo,useState} from 'react';
import {Alert,Pressable,SafeAreaView,ScrollView,StyleSheet,Switch,Text,TextInput,View} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {Picker} from '@react-native-picker/picker';
import {StatusBar} from 'expo-status-bar';
import {DepositServiceForm,DiverseServiceForm} from './LogisticsV33Screens';
import {clientLogin,clientMe,listClientRequests,createClientRequest,clientQuoteResponse} from './appApi';
const {REQUEST_KIND,REQUEST_STATUS,calculateCollectTotal,calculateDeliveryPrice,calculateExecutivePrice,createCode,nonNegativeNumber}=require('./domain');

const SESSION_KEY='goy_client_session_v4';
const PRESET_SHIPMENT='goy_client_shipment_preset_v4';
const PRESET_PROCEDURE='goy_client_procedure_preset_v4';
const C={navy:'#0B2F40',blue:'#00A9E8',green:'#38A844',red:'#C64A4A',bg:'#F3F7F9',white:'#fff',ink:'#17242D',muted:'#687984',line:'#DCE6EB'};
const money=v=>`$${Number(v||0).toFixed(2)}`;
function Field({label,multiline,...props}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput {...props} multiline={multiline} style={[s.input,multiline&&s.multiline]}/></View>}
function Button({title,onPress,kind='blue',disabled=false}){return <Pressable disabled={disabled} onPress={onPress} style={[s.button,kind==='green'&&s.green,kind==='danger'&&s.danger,disabled&&s.disabled]}><Text style={s.buttonText}>{title}</Text></Pressable>}
function Card({children}){return <View style={s.card}>{children}</View>}

function Login({onLogin}){
  const [whatsapp,setWhatsapp]=useState('');const [documentId,setDocumentId]=useState('');const [email,setEmail]=useState('');const [busy,setBusy]=useState(false);
  const submit=async()=>{if(!whatsapp.trim()||!documentId.trim()||!email.trim()){Alert.alert('Faltan datos','Completa WhatsApp, cédula/RUC y correo.');return;}setBusy(true);try{const result=await clientLogin({whatsapp,documentId,email});const session={token:result.token,expiresAt:result.expiresAt,client:result.client};await AsyncStorage.setItem(SESSION_KEY,JSON.stringify(session));onLogin(session);}catch(e){Alert.alert('No se pudo ingresar',e.message);}finally{setBusy(false)}};
  return <ScrollView contentContainerStyle={s.page}><Text style={s.eyebrow}>GOY XPRESS CLIENTE</Text><Text style={s.heading}>Tu logística en Quito</Text><Text style={s.note}>Ingresa con los datos con los que fuiste registrado por invitación.</Text><Card><Field label="WhatsApp" value={whatsapp} onChangeText={setWhatsapp} keyboardType="phone-pad"/><Field label="Cédula / RUC" value={documentId} onChangeText={setDocumentId}/><Field label="Correo" value={email} onChangeText={setEmail} keyboardType="email-address" autoCapitalize="none"/><Button title={busy?'Ingresando…':'Ingresar'} kind="green" disabled={busy} onPress={submit}/></Card></ScrollView>
}

function ShipmentForm({onDone,onCancel}){
  const [mode,setMode]=useState('scheduled'),[origin,setOrigin]=useState(''),[recipient,setRecipient]=useState(''),[destination,setDestination]=useState(''),[distance,setDistance]=useState('5'),[productValue,setProductValue]=useState('0'),[cod,setCod]=useState(true),[payer,setPayer]=useState('recipient'),[notes,setNotes]=useState(''),[savePreset,setSavePreset]=useState(false);
  const pricing=useMemo(()=>calculateDeliveryPrice(mode,distance),[mode,distance]);
  const collect=useMemo(()=>calculateCollectTotal({productValue,deliveryCost:pricing.total,cashOnDelivery:cod,deliveryPayer:payer}),[productValue,pricing.total,cod,payer]);
  useEffect(()=>{AsyncStorage.getItem(PRESET_SHIPMENT).then(raw=>{if(!raw)return;try{const p=JSON.parse(raw);setMode(p.mode||'scheduled');setOrigin(p.origin||'');setDestination(p.destination||'');setDistance(String(p.distance||5));setNotes(p.notes||'');}catch{}})},[]);
  const submit=async()=>{if(!origin.trim()||!recipient.trim()||!destination.trim()){Alert.alert('Faltan datos','Completa retiro, destinatario y entrega.');return;}if(!pricing.eligible){Alert.alert('Distancia no válida',mode==='scheduled'?'Programada aplica hasta 5 km.':'Revisa la distancia.');return;}if(savePreset)await AsyncStorage.setItem(PRESET_SHIPMENT,JSON.stringify({mode,origin,destination,distance,notes}));onDone({code:createCode(REQUEST_KIND.shipment),kind:REQUEST_KIND.shipment,deliveryMode:mode,originAddress:origin.trim(),recipient:recipient.trim(),destinationAddress:destination.trim(),distanceKm:pricing.distanceKm,productValue:nonNegativeNumber(productValue),cashOnDelivery:cod,deliveryPayer:payer,notes:notes.trim(),baseServiceCost:pricing.total,serviceCost:pricing.total,totalToCollect:collect,status:REQUEST_STATUS.pending,createdAt:new Date().toISOString()});};
  return <Card><Text style={s.title}>Entrega programada / Express</Text><View style={s.row}><Button title="Programada" kind={mode==='scheduled'?'green':'blue'} onPress={()=>setMode('scheduled')}/><Button title="Express" kind={mode==='express'?'green':'blue'} onPress={()=>setMode('express')}/></View><Field label="Punto de retiro" value={origin} onChangeText={setOrigin}/><Field label="Destinatario" value={recipient} onChangeText={setRecipient}/><Field label="Dirección de entrega" value={destination} onChangeText={setDestination} multiline/><Field label="Distancia km" value={distance} onChangeText={setDistance} keyboardType="decimal-pad"/><Field label="Valor del producto" value={productValue} onChangeText={setProductValue} keyboardType="decimal-pad"/><Text style={s.label}>Quién paga el envío</Text><View style={s.row}><Button title="Destinatario" kind={payer==='recipient'?'green':'blue'} onPress={()=>setPayer('recipient')}/><Button title="Remitente" kind={payer==='sender'?'green':'blue'} onPress={()=>setPayer('sender')}/></View><View style={s.switchRow}><Text style={s.label}>Cobro contra entrega</Text><Switch value={cod} onValueChange={setCod}/></View><Field label="Indicaciones" value={notes} onChangeText={setNotes} multiline/><View style={s.switchRow}><Text style={s.label}>Guardar como recurrente</Text><Switch value={savePreset} onValueChange={setSavePreset}/></View><Text style={s.total}>Servicio {money(pricing.total)} · Cobrar {money(collect)}</Text><Button title="Crear entrega" kind="green" onPress={submit}/><Button title="Volver" onPress={onCancel}/></Card>
}

function ProcedureForm({onDone,onCancel}){
  const [type,setType]=useState('Ingreso de documentos'),[institution,setInstitution]=useState(''),[address,setAddress]=useState(''),[minutes,setMinutes]=useState('40'),[amount,setAmount]=useState('0'),[details,setDetails]=useState(''),[savePreset,setSavePreset]=useState(false);
  const pricing=useMemo(()=>calculateExecutivePrice(minutes),[minutes]);
  useEffect(()=>{AsyncStorage.getItem(PRESET_PROCEDURE).then(raw=>{if(!raw)return;try{const p=JSON.parse(raw);setType(p.type||type);setInstitution(p.institution||'');setAddress(p.address||'');setDetails(p.details||'');}catch{}})},[]);
  const submit=async()=>{if(!institution.trim()||!address.trim()){Alert.alert('Faltan datos','Completa institución y dirección.');return;}if(savePreset)await AsyncStorage.setItem(PRESET_PROCEDURE,JSON.stringify({type,institution,address,details}));onDone({code:createCode(REQUEST_KIND.procedure),kind:REQUEST_KIND.procedure,procedureType:type,institution:institution.trim(),destinationAddress:address.trim(),waitMinutes:pricing.requestedMinutes,amountToHandle:nonNegativeNumber(amount),details:details.trim(),baseServiceCost:pricing.total,serviceCost:pricing.total,totalToCollect:0,status:REQUEST_STATUS.pending,createdAt:new Date().toISOString()});};
  return <Card><Text style={s.title}>Trámite ejecutivo</Text><Text style={s.note}>$6.50 hasta 40 minutos + $0.10 por minuto adicional.</Text><View style={s.picker}><Picker selectedValue={type} onValueChange={setType}><Picker.Item label="Ingreso de documentos" value="Ingreso de documentos"/><Picker.Item label="Retiro de documentos" value="Retiro de documentos"/><Picker.Item label="Pago de servicios" value="Pago de servicios"/><Picker.Item label="Gestión institucional" value="Gestión institucional"/></Picker></View><Field label="Institución" value={institution} onChangeText={setInstitution}/><Field label="Dirección" value={address} onChangeText={setAddress} multiline/><Field label="Tiempo estimado min" value={minutes} onChangeText={setMinutes} keyboardType="number-pad"/><Field label="Valor a manejar" value={amount} onChangeText={setAmount} keyboardType="decimal-pad"/><Field label="Instrucciones" value={details} onChangeText={setDetails} multiline/><View style={s.switchRow}><Text style={s.label}>Guardar como recurrente</Text><Switch value={savePreset} onValueChange={setSavePreset}/></View><Text style={s.total}>Tarifa estimada {money(pricing.total)}</Text><Button title="Crear trámite" kind="green" onPress={submit}/><Button title="Volver" onPress={onCancel}/></Card>
}

function ClientHome({session,onLogout}){
  const [screen,setScreen]=useState('home');const [requests,setRequests]=useState([]);const [busy,setBusy]=useState(false);
  const refresh=async()=>{try{const r=await listClientRequests(session);setRequests(r.requests||[]);}catch(e){Alert.alert('Sincronización',e.message)}};
  useEffect(()=>{refresh();const id=setInterval(refresh,60000);return()=>clearInterval(id)},[]);
  const create=async req=>{setBusy(true);try{const result=await createClientRequest(session,req);setScreen('home');Alert.alert('Solicitud creada',`${result.request.code}\nTarifa: ${money(result.request.serviceCost)}`);await refresh();}catch(e){Alert.alert('No se pudo crear',e.message)}finally{setBusy(false)}};
  const quote=async(code,response)=>{try{await clientQuoteResponse(session,code,response);await refresh();Alert.alert('Cotización',response==='accepted'?'Aceptada correctamente.':'Rechazada.');}catch(e){Alert.alert('No se pudo responder',e.message)}};
  const cancelLogout=async()=>{await AsyncStorage.removeItem(SESSION_KEY);onLogout();};
  if(screen==='shipment')return <ScrollView contentContainerStyle={s.page}><ShipmentForm onDone={create} onCancel={()=>setScreen('home')}/></ScrollView>;
  if(screen==='procedure')return <ScrollView contentContainerStyle={s.page}><ProcedureForm onDone={create} onCancel={()=>setScreen('home')}/></ScrollView>;
  if(screen==='deposit')return <ScrollView contentContainerStyle={s.page}><DepositServiceForm customer={session.client.name} phone={session.client.whatsapp} onCreate={create} onCancel={()=>setScreen('home')}/></ScrollView>;
  if(screen==='diverse')return <ScrollView contentContainerStyle={s.page}><DiverseServiceForm customer={session.client.name} phone={session.client.whatsapp} onCreate={create} onCancel={()=>setScreen('home')}/></ScrollView>;
  return <ScrollView contentContainerStyle={s.page}><Text style={s.eyebrow}>GOY XPRESS CLIENTE</Text><Text style={s.heading}>Hola, {session.client.name}</Text><Text style={s.note}>Tus pedidos, trámites y cotizaciones se sincronizan con administración.</Text><View style={s.grid}><Button title="Entrega programada / Express" onPress={()=>setScreen('shipment')}/><Button title="Trámite ejecutivo" kind="green" onPress={()=>setScreen('procedure')}/><Button title="Depósito" onPress={()=>setScreen('deposit')}/><Button title="Servicios diversos" kind="green" onPress={()=>setScreen('diverse')}/></View>{busy?<Text style={s.note}>Registrando…</Text>:null}<View style={s.row}><Button title="Actualizar" onPress={refresh}/><Button title="Cerrar sesión" kind="danger" onPress={cancelLogout}/></View><Text style={s.subtitle}>Mis solicitudes</Text>{requests.length===0?<Card><Text style={s.note}>No tienes solicitudes registradas.</Text></Card>:requests.map(r=><Card key={r.code}><Text style={s.code}>{r.code}</Text><Text style={s.title}>{r.serviceLabel||({shipment:'Entrega',procedure:'Trámite',deposit:'Depósito',diverse:'Servicio diverso'}[r.kind]||r.kind)}</Text><Text style={s.note}>Estado: {r.status} · Tarifa: {money(r.serviceCost)}</Text>{r.wait?.extraMinutes>0?<Text style={s.note}>Espera adicional: {r.wait.extraMinutes} min · {money(r.wait.extraCost)}</Text>:null}{r.kind==='diverse'&&r.quote?.status==='Cotizado'?<><Text style={s.total}>Cotización {money(r.quote.amount)}</Text><Text style={s.note}>{r.quote.note||''}</Text><View style={s.row}><Button title="Aceptar" kind="green" onPress={()=>quote(r.code,'accepted')}/><Button title="Rechazar" kind="danger" onPress={()=>quote(r.code,'rejected')}/></View></>:null}</Card>)}</ScrollView>
}

export default function ClientOnlyApp(){
  const [session,setSession]=useState(null);const [checking,setChecking]=useState(true);
  useEffect(()=>{AsyncStorage.getItem(SESSION_KEY).then(async raw=>{if(!raw){setChecking(false);return;}try{const value=JSON.parse(raw);const result=await clientMe(value);const next={...value,client:result.client};await AsyncStorage.setItem(SESSION_KEY,JSON.stringify(next));setSession(next);}catch{await AsyncStorage.removeItem(SESSION_KEY)}finally{setChecking(false)}})},[]);
  return <SafeAreaView style={s.safe}><StatusBar style="light" backgroundColor={C.navy}/><View style={s.header}><Text style={s.brand}>GOY XPRESS</Text><Text style={s.headerSub}>App Cliente</Text></View>{checking?<View style={s.center}><Text>Verificando cuenta…</Text></View>:session?<ClientHome session={session} onLogout={()=>setSession(null)}/>:<Login onLogin={setSession}/>}</SafeAreaView>
}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},header:{backgroundColor:C.navy,paddingHorizontal:18,paddingVertical:14},brand:{color:C.white,fontSize:22,fontWeight:'900'},headerSub:{color:'#B9D3DF',fontWeight:'700'},page:{padding:16,paddingBottom:50},center:{flex:1,alignItems:'center',justifyContent:'center'},eyebrow:{color:C.blue,fontWeight:'900',letterSpacing:1.2},heading:{fontSize:28,fontWeight:'900',color:C.navy,marginTop:4,marginBottom:8},subtitle:{fontSize:20,fontWeight:'900',color:C.navy,marginTop:22,marginBottom:4},title:{fontSize:17,fontWeight:'900',color:C.ink,marginBottom:5},note:{color:C.muted,lineHeight:19,marginBottom:8},card:{backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:16,padding:16,marginVertical:8},field:{marginTop:10},label:{fontWeight:'800',fontSize:12,color:C.ink,marginBottom:5},input:{borderWidth:1,borderColor:C.line,borderRadius:10,padding:11,color:C.ink,minHeight:44,backgroundColor:C.white},multiline:{minHeight:80,textAlignVertical:'top'},button:{backgroundColor:C.blue,borderRadius:11,padding:12,alignItems:'center',marginTop:9,flex:1},green:{backgroundColor:C.green},danger:{backgroundColor:C.red},disabled:{opacity:.5},buttonText:{color:C.white,fontWeight:'900',textAlign:'center'},row:{flexDirection:'row',gap:8},grid:{gap:4},switchRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:12},picker:{borderWidth:1,borderColor:C.line,borderRadius:10,overflow:'hidden',backgroundColor:C.white},total:{fontWeight:'900',fontSize:16,color:C.navy,marginTop:10},code:{fontWeight:'900',color:C.blue,marginBottom:4}});
