import React, {useEffect, useMemo, useState} from 'react';
import {Alert, Linking, Pressable, SafeAreaView, ScrollView, StyleSheet, Switch, Text, TextInput, View} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {Picker} from '@react-native-picker/picker';
import {StatusBar} from 'expo-status-bar';
import {DepositServiceForm, DiverseServiceForm} from './LogisticsV33Screens';
import {createLogisticsRequest, respondToQuote} from './logisticsApi';
import {fetchPrivateRequest} from './requestAccessApi';

const {PRICING,REQUEST_KIND,REQUEST_STATUS,calculateCollectTotal,calculateDeliveryPrice,calculateExecutivePrice,createCode,nonNegativeNumber}=require('./domain');
const STORE='goy_cliente_requests_v1';
const PROFILE='goy_cliente_profile_v1';
const PRESET_SHIPMENT='goy_cliente_preset_shipment';
const PRESET_PROCEDURE='goy_cliente_preset_procedure';
const ADMIN_WHATSAPP='593997729964';
const C={navy:'#0B2F40',blue:'#00A9E8',green:'#38A844',red:'#C64A4A',bg:'#F3F7F9',white:'#fff',ink:'#17242D',muted:'#687984',line:'#DCE6EB'};
const money=v=>`$${Number(v||0).toFixed(2)}`;
function Field({label,multiline,...props}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput {...props} multiline={multiline} style={[s.input,multiline&&s.multiline]}/></View>}
function Button({title,onPress,kind='blue',disabled=false}){return <Pressable disabled={disabled} onPress={onPress} style={[s.button,kind==='green'&&s.green,kind==='danger'&&s.danger,disabled&&s.disabled]}><Text style={s.buttonText}>{title}</Text></Pressable>}
function Card({children}){return <View style={s.card}>{children}</View>}

async function saveRecords(records){await AsyncStorage.setItem(STORE,JSON.stringify(records.slice(0,100)));}
async function notifyAdmin(request,secret){
  const msg=['GOY XPRESS - NUEVA SOLICITUD CLIENTE',`Código: ${request.code}`,`Servicio: ${request.kind}`,`Cliente: ${request.customer||'-'}`,`Valor: ${money(request.serviceCost)}`,'',`Acceso privado: ${secret}`].join('\n');
  try{await Linking.openURL(`https://wa.me/${ADMIN_WHATSAPP}?text=${encodeURIComponent(msg)}`);}catch{}
}

function ShipmentForm({profile,onDone,onCancel}){
  const [mode,setMode]=useState('scheduled'),[origin,setOrigin]=useState(''),[recipient,setRecipient]=useState(''),[destination,setDestination]=useState(''),[distance,setDistance]=useState('5'),[productValue,setProductValue]=useState('0'),[cod,setCod]=useState(true),[payer,setPayer]=useState('recipient'),[notes,setNotes]=useState(''),[savePreset,setSavePreset]=useState(false);
  const pricing=useMemo(()=>calculateDeliveryPrice(mode,distance),[mode,distance]);
  const collect=useMemo(()=>calculateCollectTotal({productValue,deliveryCost:pricing.total,cashOnDelivery:cod,deliveryPayer:payer}),[productValue,pricing.total,cod,payer]);
  useEffect(()=>{AsyncStorage.getItem(PRESET_SHIPMENT).then(raw=>{if(!raw)return;try{const p=JSON.parse(raw);setMode(p.mode||'scheduled');setOrigin(p.origin||'');setDestination(p.destination||'');setDistance(String(p.distance||5));setNotes(p.notes||'');}catch{}})},[]);
  const submit=async()=>{if(!origin.trim()||!recipient.trim()||!destination.trim())return Alert.alert('Faltan datos','Completa retiro, destinatario y dirección.');if(!pricing.eligible)return Alert.alert('Distancia no permitida','Revisa la distancia del servicio.');const request={code:createCode(REQUEST_KIND.shipment),kind:REQUEST_KIND.shipment,deliveryMode:mode,customer:profile.name,phone:profile.phone,originAddress:origin.trim(),recipient:recipient.trim(),destinationAddress:destination.trim(),distanceKm:pricing.distanceKm,productValue:nonNegativeNumber(productValue),cashOnDelivery:cod,deliveryPayer:payer,notes:notes.trim(),baseServiceCost:pricing.total,serviceCost:pricing.total,totalToCollect:collect,status:REQUEST_STATUS.pending,createdAt:new Date().toISOString()};if(savePreset)await AsyncStorage.setItem(PRESET_SHIPMENT,JSON.stringify({mode,origin,destination,distance,notes}));onDone(request);};
  return <Card><Text style={s.title}>Entrega programada / Express</Text><View style={s.row}><Button title="Programada" kind={mode==='scheduled'?'green':'blue'} onPress={()=>setMode('scheduled')}/><Button title="Express" kind={mode==='express'?'green':'blue'} onPress={()=>setMode('express')}/></View><Field label="Punto de retiro" value={origin} onChangeText={setOrigin}/><Field label="Destinatario" value={recipient} onChangeText={setRecipient}/><Field label="Dirección de entrega" value={destination} onChangeText={setDestination} multiline/><Field label="Distancia km" value={distance} onChangeText={setDistance} keyboardType="decimal-pad"/><Field label="Valor del producto" value={productValue} onChangeText={setProductValue} keyboardType="decimal-pad"/><Text style={s.label}>Quién paga el envío</Text><View style={s.row}><Button title="Destinatario" kind={payer==='recipient'?'green':'blue'} onPress={()=>setPayer('recipient')}/><Button title="Remitente" kind={payer==='sender'?'green':'blue'} onPress={()=>setPayer('sender')}/></View><View style={s.switchRow}><Text style={s.label}>Cobro contra entrega</Text><Switch value={cod} onValueChange={setCod}/></View><Field label="Indicaciones" value={notes} onChangeText={setNotes} multiline/><View style={s.switchRow}><Text style={s.label}>Guardar como entrega recurrente</Text><Switch value={savePreset} onValueChange={setSavePreset}/></View><Text style={s.total}>Servicio {money(pricing.total)} · Recaudar {money(collect)}</Text><Button title="Solicitar entrega" kind="green" onPress={submit}/><Button title="Volver" onPress={onCancel}/></Card>;
}

function ProcedureForm({profile,onDone,onCancel}){
  const [type,setType]=useState('Ingreso de documentos'),[institution,setInstitution]=useState(''),[address,setAddress]=useState(''),[minutes,setMinutes]=useState('40'),[amount,setAmount]=useState('0'),[details,setDetails]=useState(''),[savePreset,setSavePreset]=useState(false);
  const pricing=useMemo(()=>calculateExecutivePrice(minutes),[minutes]);
  useEffect(()=>{AsyncStorage.getItem(PRESET_PROCEDURE).then(raw=>{if(!raw)return;try{const p=JSON.parse(raw);setType(p.type||type);setInstitution(p.institution||'');setAddress(p.address||'');setDetails(p.details||'');}catch{}})},[]);
  const submit=async()=>{if(!institution.trim()||!address.trim())return Alert.alert('Faltan datos','Completa institución y dirección.');const request={code:createCode(REQUEST_KIND.procedure),kind:REQUEST_KIND.procedure,procedureType:type,customer:profile.name,phone:profile.phone,institution:institution.trim(),destinationAddress:address.trim(),waitMinutes:pricing.requestedMinutes,amountToHandle:nonNegativeNumber(amount),details:details.trim(),baseServiceCost:pricing.total,serviceCost:pricing.total,totalToCollect:0,status:REQUEST_STATUS.pending,createdAt:new Date().toISOString()};if(savePreset)await AsyncStorage.setItem(PRESET_PROCEDURE,JSON.stringify({type,institution,address,details}));onDone(request);};
  return <Card><Text style={s.title}>Trámite ejecutivo</Text><Text style={s.note}>$6.50 hasta 40 minutos + $0.10 por minuto adicional.</Text><View style={s.picker}><Picker selectedValue={type} onValueChange={setType}><Picker.Item label="Ingreso de documentos" value="Ingreso de documentos"/><Picker.Item label="Retiro de documentos" value="Retiro de documentos"/><Picker.Item label="Pago de servicios" value="Pago de servicios"/><Picker.Item label="Gestión institucional" value="Gestión institucional"/></Picker></View><Field label="Institución" value={institution} onChangeText={setInstitution}/><Field label="Dirección" value={address} onChangeText={setAddress} multiline/><Field label="Tiempo estimado min" value={minutes} onChangeText={setMinutes} keyboardType="number-pad"/><Field label="Valor a manejar" value={amount} onChangeText={setAmount} keyboardType="decimal-pad"/><Field label="Instrucciones" value={details} onChangeText={setDetails} multiline/><View style={s.switchRow}><Text style={s.label}>Guardar como trámite recurrente</Text><Switch value={savePreset} onValueChange={setSavePreset}/></View><Text style={s.total}>Tarifa estimada {money(pricing.total)}</Text><Button title="Solicitar trámite" kind="green" onPress={submit}/><Button title="Volver" onPress={onCancel}/></Card>;
}

export default function ClientOnlyApp(){
  const [profile,setProfile]=useState({name:'',phone:''}),[screen,setScreen]=useState('home'),[records,setRecords]=useState([]),[busy,setBusy]=useState(false);
  useEffect(()=>{Promise.all([AsyncStorage.getItem(PROFILE),AsyncStorage.getItem(STORE)]).then(([p,r])=>{try{if(p)setProfile(JSON.parse(p));}catch{}try{if(r)setRecords(JSON.parse(r));}catch{}})},[]);
  useEffect(()=>{AsyncStorage.setItem(PROFILE,JSON.stringify(profile));},[profile]);
  const valid=profile.name.trim().length>1&&String(profile.phone).replace(/\D/g,'').length>=9;
  const create=async request=>{if(!valid)return Alert.alert('Tus datos','Completa nombre/negocio y WhatsApp.');setBusy(true);try{const result=await createLogisticsRequest({...request,customer:profile.name.trim(),phone:profile.phone.trim()});if(!result.accessSecret)throw new Error('No se recibió acceso privado.');const entry={code:request.code,secret:result.accessSecret,kind:request.kind,request:result.request,createdAt:new Date().toISOString()};const next=[entry,...records.filter(x=>x.code!==entry.code)];setRecords(next);await saveRecords(next);setScreen('home');Alert.alert('Solicitud registrada',`${entry.code}\n${money(result.request?.serviceCost)}`);await notifyAdmin(result.request||request,result.accessSecret);}catch(e){Alert.alert('No se pudo registrar',e.message);}finally{setBusy(false)}};
  const refresh=async entry=>{try{const updated=await fetchPrivateRequest(entry.code,entry.secret);const next=records.map(x=>x.code===entry.code?{...x,request:updated}:x);setRecords(next);await saveRecords(next);}catch(e){Alert.alert('No se pudo actualizar',e.message)}};
  const quote=async(entry,response)=>{try{const updated=await respondToQuote(entry.code,entry.secret,response);const next=records.map(x=>x.code===entry.code?{...x,request:updated}:x);setRecords(next);await saveRecords(next);Alert.alert('Cotización',response==='accepted'?'Aceptada':'Rechazada');}catch(e){Alert.alert('No se pudo responder',e.message)}};
  const wrapper=child=><SafeAreaView style={s.safe}><StatusBar style="light" backgroundColor={C.navy}/><View style={s.header}><Text style={s.brand}>GOY XPRESS</Text><Text style={s.headerSub}>CLIENTES</Text></View><ScrollView contentContainerStyle={s.page}>{child}</ScrollView></SafeAreaView>;
  if(screen==='shipment')return wrapper(<ShipmentForm profile={profile} onDone={create} onCancel={()=>setScreen('home')}/>);
  if(screen==='procedure')return wrapper(<ProcedureForm profile={profile} onDone={create} onCancel={()=>setScreen('home')}/>);
  if(screen==='deposit')return wrapper(<DepositServiceForm customer={profile.name} phone={profile.phone} onCreate={create} onCancel={()=>setScreen('home')}/>);
  if(screen==='diverse')return wrapper(<DiverseServiceForm customer={profile.name} phone={profile.phone} onCreate={create} onCancel={()=>setScreen('home')}/>);
  return wrapper(<><Text style={s.heading}>Tu logística desde Quito</Text><Text style={s.note}>Solicita entregas y trámites. El administrador coordina la operación y tú puedes consultar el estado desde esta app.</Text><Field label="Nombre / emprendimiento" value={profile.name} onChangeText={name=>setProfile(p=>({...p,name}))}/><Field label="WhatsApp" value={profile.phone} onChangeText={phone=>setProfile(p=>({...p,phone}))} keyboardType="phone-pad"/><View style={s.grid}><Button title="Entrega programada / Express" disabled={!valid} onPress={()=>setScreen('shipment')}/><Button title="Trámite ejecutivo" kind="green" disabled={!valid} onPress={()=>setScreen('procedure')}/><Button title="Depósito" disabled={!valid} onPress={()=>setScreen('deposit')}/><Button title="Servicios diversos" kind="green" disabled={!valid} onPress={()=>setScreen('diverse')}/></View>{busy?<Text style={s.note}>Registrando…</Text>:null}<Text style={s.subtitle}>Mis solicitudes</Text>{records.length===0?<Card><Text style={s.note}>Todavía no tienes solicitudes en este teléfono.</Text></Card>:records.map(r=><Card key={r.code}><Text style={s.code}>{r.code}</Text><Text style={s.note}>{r.request?.status||'Pendiente'} · {money(r.request?.serviceCost)}</Text><Button title="Actualizar estado" onPress={()=>refresh(r)}/>{r.kind==='diverse'&&r.request?.quote?.status==='Cotizado'?<View style={s.row}><Button title="Aceptar cotización" kind="green" onPress={()=>quote(r,'accepted')}/><Button title="Rechazar" kind="danger" onPress={()=>quote(r,'rejected')}/></View>:null}</Card>)}</>);
}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},header:{backgroundColor:C.navy,paddingHorizontal:20,paddingVertical:18},brand:{color:C.white,fontWeight:'900',fontSize:22},headerSub:{color:'#BFE9F7',fontWeight:'800',fontSize:12,marginTop:2},page:{padding:16,paddingBottom:40},heading:{fontSize:26,fontWeight:'900',color:C.navy,marginBottom:6},subtitle:{fontSize:18,fontWeight:'900',color:C.ink,marginTop:22,marginBottom:6},card:{backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:16,padding:16,marginVertical:8},title:{fontSize:18,fontWeight:'900',color:C.ink,marginBottom:6},note:{color:C.muted,lineHeight:19,marginBottom:8},field:{marginTop:10},label:{fontWeight:'800',fontSize:12,color:C.ink,marginBottom:5},input:{borderWidth:1,borderColor:C.line,borderRadius:10,padding:11,color:C.ink,minHeight:44,backgroundColor:C.white},multiline:{minHeight:82,textAlignVertical:'top'},button:{backgroundColor:C.blue,borderRadius:11,padding:12,alignItems:'center',marginTop:9,flex:1},green:{backgroundColor:C.green},danger:{backgroundColor:C.red},disabled:{opacity:.45},buttonText:{color:C.white,fontWeight:'900',textAlign:'center'},row:{flexDirection:'row',gap:8},switchRow:{flexDirection:'row',justifyContent:'space-between',alignItems:'center',marginTop:10},picker:{borderWidth:1,borderColor:C.line,borderRadius:10,overflow:'hidden',backgroundColor:C.white,marginTop:8},grid:{marginTop:12},total:{fontWeight:'900',fontSize:16,color:C.navy,marginTop:10},code:{fontWeight:'900',color:C.navy,fontSize:16}});