import React, {useEffect, useState} from 'react';
import {Alert, Pressable, SafeAreaView, ScrollView, StyleSheet, Text, TextInput, View} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {StatusBar} from 'expo-status-bar';
import {CourierJobTools} from './LogisticsV33Screens';
import {fetchPrivateRequest} from './requestAccessApi';

const LAST='goy_courier_last_access_v1';
const C={navy:'#0B2F40',blue:'#00A9E8',green:'#38A844',red:'#C64A4A',bg:'#F3F7F9',white:'#fff',ink:'#17242D',muted:'#687984',line:'#DCE6EB'};
function Field({label,...props}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput {...props} style={s.input}/></View>}
function Button({title,onPress,kind='blue',disabled=false}){return <Pressable disabled={disabled} onPress={onPress} style={[s.button,kind==='green'&&s.green,kind==='danger'&&s.danger,disabled&&s.disabled]}><Text style={s.buttonText}>{title}</Text></Pressable>}
function Card({children}){return <View style={s.card}>{children}</View>}
const money=v=>`$${Number(v||0).toFixed(2)}`;

export default function CourierOnlyApp(){
  const [code,setCode]=useState(''),[secret,setSecret]=useState(''),[request,setRequest]=useState(null),[busy,setBusy]=useState(false);
  useEffect(()=>{AsyncStorage.getItem(LAST).then(raw=>{if(!raw)return;try{const p=JSON.parse(raw);setCode(p.code||'');}catch{}})},[]);
  const open=async()=>{if(!code.trim()||!secret.trim())return Alert.alert('Faltan datos','Ingresa código y acceso privado entregado por el administrador.');setBusy(true);try{const data=await fetchPrivateRequest(code.trim(),secret.trim());setRequest(data);await AsyncStorage.setItem(LAST,JSON.stringify({code:code.trim()}));}catch(e){Alert.alert('Acceso rechazado',e.message);}finally{setBusy(false)}};
  const close=()=>{setRequest(null);setSecret('');};
  return <SafeAreaView style={s.safe}><StatusBar style="light" backgroundColor={C.navy}/><View style={s.header}><Text style={s.brand}>GOY XPRESS</Text><Text style={s.headerSub}>MENSAJEROS</Text></View><ScrollView contentContainerStyle={s.page}>{request?<><Text style={s.heading}>Operación asignada</Text><Card><Text style={s.code}>{request.code}</Text><Text style={s.note}>{request.kind} · {request.status}</Text><Text style={s.total}>Tarifa {money(request.serviceCost)}</Text>{Number(request.totalToCollect||0)>0?<Text style={s.total}>Valor a recaudar {money(request.totalToCollect)}</Text>:null}</Card><CourierJobTools request={request} secret={secret} onUpdated={value=>{if(value)setRequest(value)}}/><Button title="Cerrar operación" kind="danger" onPress={close}/></>:<><Text style={s.heading}>Acceso a operación</Text><Text style={s.note}>Solo puedes abrir solicitudes que el administrador te haya asignado. Usa el código y acceso privado recibidos.</Text><Field label="Código de solicitud" value={code} onChangeText={setCode} autoCapitalize="characters"/><Field label="Acceso privado" value={secret} onChangeText={setSecret} secureTextEntry autoCapitalize="none"/><Button title={busy?'Verificando…':'Abrir operación'} kind="green" disabled={busy} onPress={open}/><Card><Text style={s.title}>Flujo de mensajero</Text><Text style={s.note}>1. Recoger y tomar fotografía.</Text><Text style={s.note}>2. Marcar En camino y activar seguimiento GPS para administración.</Text><Text style={s.note}>3. Si existe espera, usar el contador de 10 minutos; después se aplica $0.10 por minuto adicional.</Text><Text style={s.note}>4. Finalizar con fotografía de entrega y, cuando corresponda, evidencia de depósito de valores recaudados.</Text></Card></>}</ScrollView></SafeAreaView>;
}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},header:{backgroundColor:C.navy,paddingHorizontal:20,paddingVertical:18},brand:{color:C.white,fontWeight:'900',fontSize:22},headerSub:{color:'#BFE9F7',fontWeight:'800',fontSize:12,marginTop:2},page:{padding:16,paddingBottom:40},heading:{fontSize:26,fontWeight:'900',color:C.navy,marginBottom:6},card:{backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:16,padding:16,marginVertical:8},title:{fontSize:18,fontWeight:'900',color:C.ink,marginBottom:6},note:{color:C.muted,lineHeight:19,marginBottom:8},field:{marginTop:10},label:{fontWeight:'800',fontSize:12,color:C.ink,marginBottom:5},input:{borderWidth:1,borderColor:C.line,borderRadius:10,padding:11,color:C.ink,minHeight:44,backgroundColor:C.white},button:{backgroundColor:C.blue,borderRadius:11,padding:12,alignItems:'center',marginTop:9},green:{backgroundColor:C.green},danger:{backgroundColor:C.red},disabled:{opacity:.45},buttonText:{color:C.white,fontWeight:'900',textAlign:'center'},code:{fontWeight:'900',color:C.navy,fontSize:20},total:{fontWeight:'900',fontSize:15,color:C.navy,marginTop:6}});