import React,{useEffect,useRef,useState} from 'react';
import {Alert,Linking,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View} from 'react-native';
import AsyncStorage from '@react-native-async-storage/async-storage';
import {StatusBar} from 'expo-status-bar';
import {courierLogin,courierMe,listCourierJobs,courierAction,courierPhotoAction,sendCourierLocation,startCourierTracking} from './appApi';
const {calculateCourierWait}=require('./logisticsRules');

const SESSION_KEY='goy_courier_session_v4';
const ADMIN_WHATSAPP='593997729964';
const C={navy:'#0B2F40',blue:'#00A9E8',green:'#38A844',red:'#C64A4A',bg:'#F3F7F9',white:'#fff',ink:'#17242D',muted:'#687984',line:'#DCE6EB',amber:'#D88900'};
const money=v=>`$${Number(v||0).toFixed(2)}`;
function Field({label,...props}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput {...props} style={s.input}/></View>}
function Button({title,onPress,kind='blue',disabled=false}){return <Pressable disabled={disabled} onPress={onPress} style={[s.button,kind==='green'&&s.green,kind==='danger'&&s.danger,kind==='amber'&&s.amber,disabled&&s.disabled]}><Text style={s.buttonText}>{title}</Text></Pressable>}
function Card({children}){return <View style={s.card}>{children}</View>}
async function notifyAdmin(text){try{await Linking.openURL(`https://wa.me/${ADMIN_WHATSAPP}?text=${encodeURIComponent(text)}`)}catch{Alert.alert('WhatsApp','No se pudo abrir WhatsApp.')}}

function Login({onLogin}){
  const [username,setUsername]=useState(''),[password,setPassword]=useState(''),[busy,setBusy]=useState(false);
  const submit=async()=>{if(!username.trim()||!password){Alert.alert('Faltan datos','Ingresa usuario y contraseña.');return;}setBusy(true);try{const r=await courierLogin({username,password});const session={token:r.token,expiresAt:r.expiresAt,courier:r.courier};await AsyncStorage.setItem(SESSION_KEY,JSON.stringify(session));onLogin(session);}catch(e){Alert.alert('Acceso denegado',e.message)}finally{setBusy(false)}};
  return <ScrollView contentContainerStyle={s.page}><Text style={s.eyebrow}>GOY XPRESS MENSAJERO</Text><Text style={s.heading}>Acceso operativo</Text><Text style={s.note}>Usa únicamente el usuario y contraseña creados por administración.</Text><Card><Field label="Usuario" value={username} onChangeText={setUsername} autoCapitalize="none"/><Field label="Contraseña" value={password} onChangeText={setPassword} secureTextEntry/><Button title={busy?'Ingresando…':'Ingresar'} kind="green" disabled={busy} onPress={submit}/></Card></ScrollView>
}

function WaitPanel({token,job,onUpdated}){
  const [startedAt,setStartedAt]=useState(null),[seconds,setSeconds]=useState(0),[running,setRunning]=useState(false);
  useEffect(()=>{if(!running||!startedAt)return;const id=setInterval(()=>setSeconds(Math.floor((Date.now()-startedAt)/1000)),1000);return()=>clearInterval(id)},[running,startedAt]);
  const minutes=Math.floor(seconds/60);const rule=calculateCourierWait(minutes);const lastSent=useRef(-1);
  useEffect(()=>{if(!running||minutes===0||minutes===lastSent.current)return;lastSent.current=minutes;courierAction(token,job.code,'wait',{elapsedMinutes:minutes}).then(r=>onUpdated(r.job)).catch(()=>{});},[minutes,running]);
  const start=()=>{setStartedAt(Date.now());setSeconds(0);lastSent.current=-1;setRunning(true)};
  const decide=async decision=>{try{const r=await courierAction(token,job.code,'wait-decision',{decision});onUpdated(r.job);if(decision==='withdraw')setRunning(false);}catch(e){Alert.alert('Espera',e.message)}};
  return <Card><Text style={s.title}>Tiempo de espera</Text><Text style={s.timer}>{String(Math.floor(seconds/60)).padStart(2,'0')}:{String(seconds%60).padStart(2,'0')}</Text><Text style={s.note}>10 minutos incluidos. Desde el minuto 11 se suman $0.10 por minuto.</Text><Text style={s.total}>Recargo actual: {money(rule.extraCost)}</Text>{!running?<Button title="Iniciar espera" onPress={start}/>:<Button title="Detener contador" kind="amber" onPress={()=>setRunning(false)}/>} {rule.requiresDecision?<><Button title="Avisar novedad al administrador por WhatsApp" kind="green" onPress={()=>notifyAdmin(`GOY XPRESS - Novedad de espera\nSolicitud: ${job.code}\nSe cumplieron 10 minutos de espera. Mensajero: requiere instrucción.`)}/><View style={s.row}><Button title="Me retiro" kind="danger" onPress={()=>decide('withdraw')}/><Button title="Continuar esperando" kind="green" onPress={()=>decide('continue')}/></View></>:null}</Card>
}

function JobDetail({session,job:initial,onBack,onChanged}){
  const [job,setJob]=useState(initial),[busy,setBusy]=useState(false),[tracking,setTracking]=useState(false);const stopRef=useRef(null);
  useEffect(()=>()=>{if(stopRef.current)stopRef.current()},[]);
  const apply=async fn=>{setBusy(true);try{const value=await fn();const next=value?.job||value;if(next){setJob(next);onChanged?.(next);}return next;}catch(e){Alert.alert('No se pudo completar',e.message);return null;}finally{setBusy(false)}};
  const pickup=async()=>{const next=await apply(()=>courierPhotoAction(session.token,job.code,'pickup'));if(next)await notifyAdmin(`GOY XPRESS - Constancia de recogida\nSolicitud: ${job.code}\nMensajero: ${session.courier.name}\nLa foto quedó registrada en administración.`)};
  const delivery=async()=>{const next=await apply(()=>courierPhotoAction(session.token,job.code,'delivery'));if(next){if(stopRef.current){stopRef.current();stopRef.current=null;setTracking(false)}await notifyAdmin(`GOY XPRESS - Entrega finalizada\nSolicitud: ${job.code}\nMensajero: ${session.courier.name}\nLa foto de entrega quedó registrada.`)}};
  const toggleTracking=async()=>{if(tracking){if(stopRef.current)stopRef.current();stopRef.current=null;setTracking(false);return;}try{stopRef.current=await startCourierTracking(session.token,job.code,next=>{setJob(next);onChanged?.(next)},e=>console.warn(e));setTracking(true);}catch(e){Alert.alert('GPS',e.message)}};
  const deposit=async amount=>apply(()=>courierPhotoAction(session.token,job.code,'deposit-evidence',{amount}));
  return <ScrollView contentContainerStyle={s.page}><Text style={s.eyebrow}>OPERACIÓN ASIGNADA</Text><Text style={s.heading}>{job.code}</Text><Card><Text style={s.title}>{job.serviceLabel||({shipment:'Entrega',procedure:'Trámite',deposit:'Depósito',diverse:'Servicio diverso'}[job.kind]||job.kind)}</Text><Text style={s.note}>Cliente: {job.customer||'-'}</Text><Text style={s.note}>Retiro: {job.originAddress||job.institution||'-'}</Text><Text style={s.note}>Destino: {job.destinationAddress||'-'}</Text><Text style={s.note}>Estado: {job.status}</Text><Text style={s.total}>Tarifa: {money(job.serviceCost)}{Number(job.totalToCollect||0)>0?` · Recaudar: ${money(job.totalToCollect)}`:''}</Text></Card><Button title="1. Recogido · tomar foto" disabled={busy||['Recogido','En camino','Entrega finalizada'].includes(job.status)} onPress={pickup}/><Button title="Enviar ubicación ahora" kind="green" disabled={busy||job.status==='Entrega finalizada'} onPress={()=>apply(()=>sendCourierLocation(session.token,job.code))}/><Button title={tracking?'Detener seguimiento GPS':'2. En camino · iniciar seguimiento GPS'} kind={tracking?'danger':'green'} disabled={job.status==='Entrega finalizada'} onPress={toggleTracking}/>{tracking?<Text style={s.tracking}>● GPS activo: administración recibe ubicación cada 30 s o 25 m. El cliente no puede verla.</Text>:null}{job.kind==='deposit'?<Button title="Foto de cheques / depósito" onPress={()=>deposit(job.cashAmount||0)}/>:null}<WaitPanel token={session.token} job={job} onUpdated={next=>{setJob(next);onChanged?.(next)}}/><Button title="3. Entrega finalizada · tomar foto" kind="green" disabled={busy||job.status==='Entrega finalizada'} onPress={delivery}/>{Number(job.totalToCollect||0)>0?<Button title="Foto de depósito de valores recaudados" onPress={()=>deposit(job.totalToCollect)}/>:null}<Button title="Volver a mis trabajos" onPress={onBack}/></ScrollView>
}

function CourierHome({session,onLogout}){
  const [jobs,setJobs]=useState([]),[selected,setSelected]=useState(null),[loading,setLoading]=useState(false);
  const refresh=async()=>{setLoading(true);try{const r=await listCourierJobs(session.token);setJobs(r.jobs||[]);if(selected){const updated=(r.jobs||[]).find(j=>j.code===selected.code);if(updated)setSelected(updated)}}catch(e){Alert.alert('Sincronización',e.message)}finally{setLoading(false)}};
  useEffect(()=>{refresh();const id=setInterval(refresh,45000);return()=>clearInterval(id)},[]);
  const logout=async()=>{await AsyncStorage.removeItem(SESSION_KEY);onLogout()};
  const changed=next=>{setSelected(next);setJobs(list=>list.map(j=>j.code===next.code?next:j))};
  if(selected)return <JobDetail session={session} job={selected} onBack={()=>{setSelected(null);refresh()}} onChanged={changed}/>;
  return <ScrollView contentContainerStyle={s.page}><Text style={s.eyebrow}>GOY XPRESS MENSAJERO</Text><Text style={s.heading}>Hola, {session.courier.name}</Text><Text style={s.note}>Solo aparecen operaciones asignadas a tu cuenta por administración.</Text><View style={s.row}><Button title={loading?'Actualizando…':'Actualizar'} onPress={refresh}/><Button title="Cerrar sesión" kind="danger" onPress={logout}/></View><Text style={s.subtitle}>Mis trabajos</Text>{jobs.length===0?<Card><Text style={s.note}>No tienes trabajos asignados.</Text></Card>:jobs.map(j=><Pressable key={j.code} onPress={()=>setSelected(j)}><Card><Text style={s.code}>{j.code}</Text><Text style={s.title}>{j.customer||'-'} · {j.status}</Text><Text style={s.note}>{j.destinationAddress||j.institution||'Sin dirección'}</Text><Text style={s.total}>{money(j.serviceCost)}</Text></Card></Pressable>)}</ScrollView>
}

export default function CourierOnlyApp(){
  const [session,setSession]=useState(null),[checking,setChecking]=useState(true);
  useEffect(()=>{AsyncStorage.getItem(SESSION_KEY).then(async raw=>{if(!raw){setChecking(false);return;}try{const value=JSON.parse(raw);const r=await courierMe(value.token);const next={...value,courier:r.courier};await AsyncStorage.setItem(SESSION_KEY,JSON.stringify(next));setSession(next);}catch{await AsyncStorage.removeItem(SESSION_KEY)}finally{setChecking(false)}})},[]);
  return <SafeAreaView style={s.safe}><StatusBar style="light" backgroundColor={C.navy}/><View style={s.header}><Text style={s.brand}>GOY XPRESS</Text><Text style={s.headerSub}>App Mensajero</Text></View>{checking?<View style={s.center}><Text>Verificando acceso…</Text></View>:session?<CourierHome session={session} onLogout={()=>setSession(null)}/>:<Login onLogin={setSession}/>}</SafeAreaView>
}

const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.bg},header:{backgroundColor:C.navy,paddingHorizontal:18,paddingVertical:14},brand:{color:C.white,fontSize:22,fontWeight:'900'},headerSub:{color:'#B9D3DF',fontWeight:'700'},page:{padding:16,paddingBottom:50},center:{flex:1,alignItems:'center',justifyContent:'center'},eyebrow:{color:C.blue,fontWeight:'900',letterSpacing:1.1},heading:{fontSize:28,fontWeight:'900',color:C.navy,marginTop:4,marginBottom:8},subtitle:{fontSize:20,fontWeight:'900',color:C.navy,marginTop:20},title:{fontSize:17,fontWeight:'900',color:C.ink,marginBottom:5},note:{color:C.muted,lineHeight:19,marginBottom:6},card:{backgroundColor:C.white,borderWidth:1,borderColor:C.line,borderRadius:16,padding:16,marginVertical:8},field:{marginTop:10},label:{fontWeight:'800',fontSize:12,color:C.ink,marginBottom:5},input:{borderWidth:1,borderColor:C.line,borderRadius:10,padding:11,color:C.ink,minHeight:44,backgroundColor:C.white},button:{backgroundColor:C.blue,borderRadius:11,padding:12,alignItems:'center',marginTop:9,flex:1},green:{backgroundColor:C.green},danger:{backgroundColor:C.red},amber:{backgroundColor:C.amber},disabled:{opacity:.45},buttonText:{color:C.white,fontWeight:'900',textAlign:'center'},row:{flexDirection:'row',gap:8},total:{fontWeight:'900',fontSize:16,color:C.navy,marginTop:7},timer:{fontSize:34,fontWeight:'900',color:C.navy,textAlign:'center',marginVertical:8},tracking:{color:C.green,fontWeight:'800',fontSize:12,marginTop:8,lineHeight:17},code:{fontWeight:'900',color:C.blue,marginBottom:4}});
