import React,{useEffect,useState}from'react';
import{Alert,Image,Pressable,SafeAreaView,ScrollView,StyleSheet,Text,TextInput,View}from'react-native';
import AsyncStorage from'@react-native-async-storage/async-storage';
import{StatusBar}from'expo-status-bar';
import CourierAppV15 from'./CourierAppV15';
import{login,pickCourierPhoto,registerCourier}from'./goyApiV5';
const KEY='goy_courier_session_v13';
const C={navy:'#071C2A',navy2:'#0B2F40',green:'#38A844',white:'#fff',cyan:'#00A9E8',muted:'#BFD8E2',line:'#2A5365'};
function Field({label,...p}){return <View style={s.field}><Text style={s.label}>{label}</Text><TextInput {...p} placeholderTextColor="#78909B" style={s.input}/></View>}
function Btn({title,onPress,disabled=false,outline=false}){return <Pressable disabled={disabled} onPress={onPress} style={[s.btn,outline&&s.outline,disabled&&{opacity:.5}]}><Text style={[s.btnText,outline&&s.outlineText]}>{title}</Text></Pressable>}
function Auth({onOk}){const[mode,setMode]=useState('login'),[busy,setBusy]=useState(false),[photo,setPhoto]=useState(''),[f,setF]=useState({name:'',phone:'',email:'',password:''});const set=(k,v)=>setF(x=>({...x,[k]:v}));const choose=async camera=>{try{const v=await pickCourierPhoto(camera);if(v)setPhoto(v)}catch(e){Alert.alert('Foto',e.message)}};const submit=async()=>{if(!f.email.trim()||!f.password)return Alert.alert('Faltan datos','Ingresa correo y contraseña.');if(mode==='register'&&(!f.name.trim()||!f.phone.trim()))return Alert.alert('Faltan datos','Completa nombre y WhatsApp.');setBusy(true);try{if(mode==='register'){await registerCourier({...f,photo,email:f.email.trim(),phone:f.phone.trim()});Alert.alert('Registro enviado','Administración debe aprobar tu cuenta antes de habilitar tus rutas.');setMode('login');return}const r=await login('courier',f.email.trim(),f.password);await AsyncStorage.setItem(KEY,JSON.stringify({token:r.token}));onOk(r.token)}catch(e){Alert.alert('GOY XPRESS',e.message)}finally{setBusy(false)}};return <SafeAreaView style={s.safe}><StatusBar style="light" backgroundColor={C.navy}/><ScrollView contentContainerStyle={s.page}><Image source={require('../assets/goy-logo.jpg')} style={s.logo}/><Text style={s.kicker}>MENSAJERO GOY XPRESS</Text><Text style={s.title}>GOY XPRESS</Text><View style={s.panel}><View style={s.segment}><Pressable onPress={()=>setMode('login')} style={[s.seg,mode==='login'&&s.segOn]}><Text style={s.segText}>Ingresar</Text></Pressable><Pressable onPress={()=>setMode('register')} style={[s.seg,mode==='register'&&s.segOn]}><Text style={s.segText}>Registrarme</Text></Pressable></View>{mode==='register'?<><View style={s.photoRow}>{photo?<Image source={{uri:photo}} style={s.avatar}/>:<View style={s.avatarEmpty}><Text style={s.avatarText}>GX</Text></View>}<View style={{flex:1}}><Btn title="Elegir foto" outline onPress={()=>choose(false)}/><Btn title="Tomar foto" outline onPress={()=>choose(true)}/></View></View><Field label="Nombre completo" value={f.name} onChangeText={v=>set('name',v)}/><Field label="WhatsApp" keyboardType="phone-pad" value={f.phone} onChangeText={v=>set('phone',v)}/></>:null}<Field label="Correo" keyboardType="email-address" autoCapitalize="none" value={f.email} onChangeText={v=>set('email',v)}/><Field label="Contraseña" secureTextEntry autoCapitalize="none" value={f.password} onChangeText={v=>set('password',v)}/><Btn title={busy?'Procesando…':mode==='register'?'Enviar registro':'Ingresar'} disabled={busy} onPress={submit}/></View></ScrollView></SafeAreaView>}
export default function CourierAppV16(){const[token,setToken]=useState(null),[loading,setLoading]=useState(true);useEffect(()=>{let alive=true;AsyncStorage.getItem(KEY).then(raw=>{if(alive)setToken(raw?JSON.parse(raw)?.token||null:null)}).finally(()=>alive&&setLoading(false));const timer=setInterval(()=>AsyncStorage.getItem(KEY).then(raw=>{const t=raw?JSON.parse(raw)?.token||null:null;if(alive)setToken(t)}).catch(()=>{}),800);return()=>{alive=false;clearInterval(timer)}},[]);if(loading)return <SafeAreaView style={s.loading}><Image source={require('../assets/goy-logo.jpg')} style={s.logo}/><Text style={s.loadingText}>GOY XPRESS</Text></SafeAreaView>;if(!token)return <Auth onOk={setToken}/>;return <CourierAppV15/>}
const s=StyleSheet.create({safe:{flex:1,backgroundColor:C.navy},page:{minHeight:'100%',backgroundColor:C.navy,padding:18,paddingTop:35,alignItems:'center'},loading:{flex:1,backgroundColor:C.navy,alignItems:'center',justifyContent:'center'},loadingText:{color:C.white,fontSize:24,fontWeight:'900',marginTop:10},logo:{width:92,height:92,borderRadius:24},kicker:{color:'#8CE6FF',fontSize:10,fontWeight:'900',marginTop:12},title:{color:C.white,fontSize:31,fontWeight:'900',marginTop:4},panel:{width:'100%',backgroundColor:C.navy2,borderRadius:24,padding:16,borderWidth:1,borderColor:C.line,marginTop:20},segment:{flexDirection:'row',backgroundColor:'#061923',padding:4,borderRadius:14},seg:{flex:1,padding:10,alignItems:'center',borderRadius:11},segOn:{backgroundColor:'#17465A'},segText:{color:C.white,fontWeight:'900'},field:{marginTop:11},label:{color:'#DDF3FA',fontWeight:'800',fontSize:12,marginBottom:6},input:{backgroundColor:'#F8FCFD',borderRadius:13,padding:12,color:'#132B36',minHeight:48},btn:{backgroundColor:C.green,borderRadius:13,minHeight:47,alignItems:'center',justifyContent:'center',paddingHorizontal:13,marginTop:10},btnText:{color:C.white,fontWeight:'900'},outline:{backgroundColor:'transparent',borderWidth:1,borderColor:'#7EC8DE'},outlineText:{color:'#A9E7F7'},photoRow:{flexDirection:'row',gap:12,alignItems:'center',marginTop:10},avatar:{width:72,height:72,borderRadius:36},avatarEmpty:{width:72,height:72,borderRadius:36,backgroundColor:'#17465A',alignItems:'center',justifyContent:'center'},avatarText:{color:C.white,fontWeight:'900',fontSize:20}});